_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 11
                - 49
                - 53
                - 55
                - 106
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 106
            "3":
                - 13
                - 16
                - 23
                - 24
                - 55
            "4": 3.10.15
            "5": 0.19.0
            "6": 4.9.2
            "8":
                - 2
                - 5
            "12": 0.19.0
            "13": linux-x86_64
epochs:
    value: 10
learning_rate:
    value: 3e-05
